### ISSUE TITLE
Calling with -inverted -bw only does -bw

### ISSUE THREAD

**Issue by Waves-rgb** [ahhhh6980/FractalC#2]
The expected result of calling `./FractalC.exe -bw -inverted` is to get a black and white image with the black and whites swapped but instead you get just the outcome of `-bw`

**Comment by ahhhh6980** [comment]
This is because the result of calling -inverted is taking 255-color, whereas typical coloring just passes color. The -inverted flag will be reimplemented in a future release in a way that actually returns an inverted color scheme. But for now it is specific to just the coloring.

**Comment by ahhhh6980** [comment]
Fixed in v0.5b-1
